<?xml version="1.0" encoding="utf-8"?><Database Name="AMNHAC" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-MB0PCOPJ;Initial Catalog=AMNHAC;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DefaultConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Playlist" Member="Playlists">
    <Type Name="Playlist">
      <Column Name="idmusic" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="namemusic" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="singer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="hinhmusic" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Video" Member="Videos">
    <Type Name="Video">
      <Column Name="id" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="author" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="link" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="hinh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>